// Generates seed SQL for a fresh D1 database: reference flats, discussion
// boards, and the admin account (PBKDF2-hashed, matching src/utils/hash.ts).
// Output goes to scripts/seed.sql, applied via `pnpm --filter server seed:local`
// or `seed:remote`. Admin credentials come from env (ADMIN_EMAIL / ADMIN_PASSWORD
// / ADMIN_NAME), defaulting to the dev values.
//
// Flats + boards use plain INSERTs (intended for a fresh DB, run once). The admin
// row is idempotent (INSERT ... WHERE NOT EXISTS).

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))

const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'admin@yuenvoice.app'
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'admin123'
const ADMIN_NAME = process.env.ADMIN_NAME || 'System Admin'

// ── PBKDF2 hashing (identical params to src/utils/hash.ts) ──
async function hashPassword(plain) {
  const salt = crypto.getRandomValues(new Uint8Array(16))
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(plain), 'PBKDF2', false, [
    'deriveBits',
  ])
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: 600_000, hash: 'SHA-256' },
    key,
    256,
  )
  const b64 = (b) => {
    const a = new Uint8Array(b)
    let s = ''
    for (const x of a) s += String.fromCharCode(x)
    return btoa(s)
  }
  return `pbkdf2-sha256$600000$${b64(salt)}$${b64(bits)}`
}

const sqlStr = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`)
const now = '2026-01-01T00:00:00.000Z'

function flatPassword() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
  const bytes = crypto.getRandomValues(new Uint8Array(8))
  let pw = ''
  for (let i = 0; i < 8; i++) pw += chars[bytes[i] % chars.length]
  return pw
}

// Multi-row INSERT batches to keep statements reasonable.
function batchedInsert(table, columns, rows, batchSize = 100) {
  const out = []
  for (let i = 0; i < rows.length; i += batchSize) {
    const chunk = rows.slice(i, i + batchSize)
    const values = chunk.map((r) => `(${columns.map((c) => sqlStr(r[c])).join(',')})`).join(',\n')
    out.push(`INSERT INTO ${table} (${columns.join(',')}) VALUES\n${values};`)
  }
  return out.join('\n')
}

async function main() {
  const lines = ['-- YuenVoice D1 seed (generated by scripts/seed.mjs)']

  // Flats: 6 blocks x 35 floors x 10 units
  const blocks = ['1', '2', '3', '4', '5', '6']
  const floors = Array.from({ length: 35 }, (_, i) => String(i + 1))
  const units = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K']
  const flats = []
  for (const block of blocks)
    for (const floor of floors)
      for (const unit of units)
        flats.push({
          id: crypto.randomUUID(),
          block,
          floor,
          unit_number: unit,
          registration_password: flatPassword(),
          is_registration_open: 1,
          created_at: now,
          updated_at: now,
        })
  lines.push(
    batchedInsert(
      'flats',
      ['id', 'block', 'floor', 'unit_number', 'registration_password', 'is_registration_open', 'created_at', 'updated_at'],
      flats,
    ),
  )

  // Discussion boards: 1 estate + 6 block boards
  const boards = [
    { id: crypto.randomUUID(), name: 'Estate General / 屋苑綜合討論', scope_type: 'estate', scope_block: null, scope_floor: null, created_at: now },
  ]
  for (let b = 1; b <= 6; b++)
    boards.push({ id: crypto.randomUUID(), name: `Block ${b} / 第${b}座討論`, scope_type: 'block', scope_block: String(b), scope_floor: null, created_at: now })
  lines.push(batchedInsert('discussion_boards', ['id', 'name', 'scope_type', 'scope_block', 'scope_floor', 'created_at'], boards))

  // Admin account (idempotent).
  const adminHash = await hashPassword(ADMIN_PASSWORD)
  lines.push(
    `INSERT INTO users (id, email, phone, password_hash, name, flat_id, role, is_active, created_at, updated_at)\n` +
      `SELECT ${sqlStr(crypto.randomUUID())}, ${sqlStr(ADMIN_EMAIL)}, NULL, ${sqlStr(adminHash)}, ${sqlStr(ADMIN_NAME)}, NULL, 'admin', 1, ${sqlStr(now)}, ${sqlStr(now)}\n` +
      `WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = ${sqlStr(ADMIN_EMAIL)});`,
  )

  const outPath = join(__dirname, 'seed.sql')
  writeFileSync(outPath, lines.join('\n\n') + '\n', 'utf8')
  console.log(`Wrote ${outPath} (${flats.length} flats, ${boards.length} boards, admin ${ADMIN_EMAIL})`)
}

main()
